apiVersion: v1
kind: Service
metadata:
  name: {{ include "rehydration-kernel.fullname" . }}
  labels:
    {{- include "rehydration-kernel.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "rehydration-kernel.selectorLabels" . | nindent 4 }}
  ports:
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      protocol: TCP
      targetPort: grpc
